name: Unity Build

on:
  push:
    branches:
      - cam-AI

  pull_request:
    branches:
      - cam-AI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Workflow
        run: |
          echo "Unity CI Pipeline Started"
          ls